[package]
name = "twistid_mersenne"
version = "0.1.0"
authors = ["Nicholas Labarre <bitbucket@ndlr.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
